shopware_app:
  metadata:
    version: 1.0.0
    name: '%env(APP_NAME)%'
    label:
      default: english label
      de-DE: german label
    description:
      default: english description
      de-DE: german description
    author: shopware AG
    copyright: (c) by shopware AG
    license: MIT
  setup:
    secret: '%env(APP_SECRET)%'